### ISSUE TITLE
DPY-4010 python-oracledb misinterpreting string literal as BIND variable

### ISSUE THREAD

**Issue by mikemulhearn** [oracle/python-oracledb#208]
1. What versions are you using?

```oracle db version: Oracle DB 12c Enterprise Edition 12.2.0.1.0
python-oracledb version: 1.3.2

platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.10.7

oracledb.__version__: 1.3.2
```

2. Is it an error or a hang or a crash?

Error

3. What error(s) or behavior you are seeing?

The library appears to be incorrectly interpreting a query that works as-is in SQL developer. One of the sub-queries within a decode function in the SELECT clause containing a string with a colon (enclosed between single quotes) appears to be attempting to be interpreted as a BIND variable, when it is only a hardcoded string.

Affected Clause:

```
DECODE((SELECT  1 
			FROM argus_app.case_classifications cc,
			     argus_app.lm_case_classification lcc
		   WHERE cc.classification_id = lcc.classification_id
		     AND UPPER(lcc.description) = 'CONSENT TO FU GRANTED'
			 AND cc.deleted is null
			 AND lcc.deleted is null
			 AND cc.case_id = cmas.case_id),1,'Yes',
		  (SELECT  1 
			FROM argus_app.case_classifications cc,
			     argus_app.lm_case_classification lcc
		   WHERE cc.classification_id = lcc.classification_id
		     AND UPPER(lcc.description) LIKE 'FU: CONSENT GRANTED'
			 AND cc.deleted is null
			 AND lcc.deleted is null
			 AND cc.case_id = cmas.case_id),1,'Yes') "FU_POSSIBLE"
```

Full Query:

https://gist.github.com/mikemulhearn/3fa6ab5a6a4636284d637ee6b5f305d8

Python Command (standard query execution):

```
conn = oracledb.connect(user=username, password=password, dsn=dsn_tns, threaded=True)
curs = conn.cursor()
curs.execute(query)
```

Error:

```
DPY-4010: a bind variable replacement value for placeholder ":CONSENT" was not provided
Traceback (most recent call last):
  File "C:\Users\mm3fa7782\PycharmProjects\oracle_extract\oracle_extract.py", line 286, in oracle_plsql_extract
    curs.execute(cnt_query)
  File "C:\Users\mm3fa7782\PycharmProjects\oracle_extract\venv\lib\site-packages\oracledb\cursor.py", line 378, in execute
    impl.execute(self)
  File "src\oracledb\impl/thin/cursor.pyx", line 135, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src\oracledb\impl/thin/cursor.pyx", line 128, in oracledb.thin_impl.ThinCursorImpl._preprocess_execute
  File "C:\Users\mm3fa7782\PycharmProjects\oracle_extract\venv\lib\site-packages\oracledb\errors.py", line 118, in _raise_err
    raise exc_type(_Error(message)) from cause
oracledb.exceptions.DatabaseError: DPY-4010: a bind variable replacement value for placeholder ":CONSENT" was not provided
```

4. Does your application call init_oracle_client()?

Yes, I have attempted to use both the Thick client (default) and the Thin client, with the same result.

5. Include a runnable Python script that shows the problem.

The above full query should be able to run through the python-oracledb query interpreter to show that it is finding a BIND variable that should not exist. Due to the complexity of the above query, I would prefer not to provide a schema to create the example here, if at all possible. This error appears to be happening by the statement interpreter and hopefully should not need a database to query.

**Comment by anthony-tuininga** [comment]
I know the source of the issue: this line in your SQL

```
CCOM.COMMENT_TXT "Reporter's Comments",
```

has an embedded quote. Since constant strings are removed first (without regard to such quoting) everything is off by one and the `FU: CONSENT` value is treated as a bind variable. If you remove that embedded quote all will work as expected. Going the other way (looking at quoted values first) won't help the situation. This limitation has been known but was not considered too likely and the changes required to support it are considerable so it was not a priority. Is making the change I mentioned a reasonable workaround? I will look into what is needed to resolve it properly but I'm not sure when that will be accomplished at this point!

**Comment by anthony-tuininga** [comment]
@mikemulhearn, I have just pushed a patch that resolves the embedded quote situation as well as improves a number of other things.

**Comment by Stephano120** [comment]
I have a similar issue when oracle functions such as DECODE or NVL are put an even number of times before a string containing a ":". I also use oracledb 1.3.2, but with python 3.11.

Typically, a query like:

`res = oracle()res = `

**Comment by anthony-tuininga** [comment]
@Stephano120, I tried it and it works. :-)

**Comment by Stephano120** [comment]
@anthony-tuininga I installed oracledb 1.4 but the problem remains.
For the time being it is necessary to copy/paste manually the patched version available on https://github.com/oracle/python-oracledb/commit/e861b2bbdca5ddbde5ae293e973da552116d7037 ?

**Comment by Stephano120** [comment]
Thanks for your swift replies @anthony-tuininga 
Please apologize my newbiness regarding some of the concepts involved here, but my oracledb folder in my venv/Lib/site-packages does not contain the impl folder which I thought would contain the thin, thick, base folder, etc, ie the structure that I see on https://github.com/oracle/python-oracledb/tree/main/src/oracledb
I can't find the statement file neither, very likely because I'm not looking at the right place. 
I guess I'll Google a bit and learn more about the concepts at stake here.
Thanks for the patch any way.

**Comment by anthony-tuininga** [comment]
You will need to build from source by following [these instructions](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code). You can't use a binary installation (which is what is found in site-packages).

**Comment by Stephano120** [comment]
Thanks !

**Comment by anthony-tuininga** [comment]
This was included in version 1.4.1 which was just released.

**Comment by Stephano120** [comment]
Great, thanks for the update!
